### ISSUE TITLE
Back button doesn't respond, back key works fine.

### ISSUE THREAD

**Issue by tankcong** [jariz/MaterialUp#11]
![image](https://cloud.githubusercontent.com/assets/1585445/8766143/a4f839ba-2e5e-11e5-81f2-7174c11af9ee.png)
select home page list item, then you will see...

**Comment by jariz** [comment]
Please keep in mind that this is app is still very early in development, so this simply hasn't been implemented yet.
See [CONTRIBUTING](https://github.com/jariz/MaterialUp/blob/master/CONTRIBUTING.md).
