### ISSUE TITLE
Toolbar below system statusbar

### ISSUE THREAD

**Issue by shaunidiot** [jariz/MaterialUp#12]
![Image](http://i.imgur.com/ygv9CTP.png)

Asus Zenphone 2 Android v5.0.1

Not sure if it's due to `android:fitsSystemWindows="true"` in the layout files. Same problem found (and maybe fix found) at https://github.com/chrisbanes/cheesesquare/pull/12.

My apologies if this doesn't fit the contributing rules..

**Comment by gaara87** [comment]
The product page is still under active development :)

**Comment by shaunidiot** [comment]
Fair enough. Was just giving a heads up as it seems to be affecting Lollipop and above. Will close for now. Thanks! :)
