### ISSUE TITLE
Why do so many dependencies?

### ISSUE THREAD

**Issue by zerolx** [jariz/MaterialUp#3]
I am seeing the code and i see that have so many dependencies, proguard is not enabled and the main method of the api is using Jsoup, that is good if the site dont provide one api, take a look: http://www.materialup.com/posts.json , materialup is build over Rails, then by default adding '.json' to the end return the result in json.

I am writting to know if have one cause to it, if don't have, i would change.

**Comment by jariz** [comment]
1. we're still in an early stage where we're still deciding on what to keep. You're not wrong, there's a lot of dependencies, but right now we're still experimenting a lot with stuff that might get removed later on.  
2. I did not know that, but that still can't be called an 'API'. It just gives you the HTML in a JSON object, which means we'd have to parse it regardless.  
   We're working very close with the admin of MaterialUp to get us a proper API.  
3. I don't understand your last sentence.

**Comment by zerolx** [comment]
Yes, you are right, that was a bad example, the json returned by the material doesn't is good, but still in smaller size , i think. Well, the admin of materialup can format the data in controller "post" for the rails return right json, the rails make the rest. 

Thanks
